### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by bryant-the-coder** [Furkanzmc/sekme.nvim#1]
How do you configure powershell that way?

**Comment by Furkanzmc** [comment]
You can take a look at my dotfiles: https://github.com/Furkanzmc/dotfiles/tree/master/pwsh

You can test it out as a drop-in replacement for your config and just remove things you don't like. 

Git prompt works asynchronously, otherwise it's a huge pain for big projects.

**Comment by bryant-the-coder** [comment]
You are using window terminal preview? Are you using oh my zsh???

**Comment by Furkanzmc** [comment]
I only use PSReadLine for a few things. Otherwise All off or is just my own configuration.

I use Windows Terminal but the screencast is from macOS.

**Comment by bryant-the-coder** [comment]
Noted
