### ISSUE TITLE
Another completion chain plugin vim-mucomplete

### ISSUE THREAD

**Issue by kiryph** [Furkanzmc/sekme.nvim#2]
Did you also know [vim-mucomplete](https://github.com/lifepillar/vim-mucomplete)?

Maybe it makes sense to add mucomplete to https://github.com/Furkanzmc/sekme.nvim/blob/master/README.md#related-projects as well.

**Comment by Furkanzmc** [comment]
I had forgotten about that. completion-nvim also mentions that as an inspiration behind the project as well. I'll add it to the list. Thanks for mentioning it.
