### ISSUE TITLE
Installation failed with packer.nvim

### ISSUE THREAD

**Issue by abjutus** [Furkanzmc/sekme.nvim#3]
[Problem]
When I try to install with `packer.nvim` and execute command `:PackerInstall`

[Config]
`use 'Furkanzmc/sekme.nvim'`

[Error message]
`[packer.nvim] [ERROR ...] async.lua:20: Error in coroutin...: Vim(execute):E121: Undefined variable: g:sekme_completion_key`

**Comment by Furkanzmc** [comment]
Hi.

Thanks for creating the issue. I just pushed a fix for it, can you check if it fixes your problem?
Sorry you encountered it. I don't use packer and didn't notice the problem.

**Comment by abjutus** [comment]
Hi, @Furkanzmc 

Thanks for fixing the issue so quickly, and it works!
Never mind, I also migrate to packer recently 😄 
I'll have fun with your plugins !!!
