### ISSUE TITLE
api.nvim_buf_get_var throws error if variable is uninitialized

### ISSUE THREAD

**Issue by jose-elias-alvarez** [Furkanzmc/sekme.nvim#4]
With a minimal setup (installing sekme.nvim without options.nvim and calling `require("sekme").setup()`, requesting completion fails with the following error:

```
Error executing vim.schedule lua callback: ...are/nvim/site/pack/packer/start/sekme.nvim/lua/sekme.lua:242: Key not found: sekme_completion_timeout
```

This is coming from [this line](https://github.com/Furkanzmc/sekme.nvim/blob/4e1331805426d6de0c17892074d67f0c614911b8/lua/sekme.lua#L242), and I think the root cause is that `api.nvim_buf_get_var` throws an error when the variable is uninitialized. 

It's pretty easy to get around the issue by using something like `vim.cmd("autocmd BufEnter * let b:sekme_completion_timeout = 150")`, but it might provide a better out-of-the-box experience to either initialize the variable through the plugin or wrap the API call in `pcall`.

**Comment by Furkanzmc** [comment]
Thanks for reporting!

The optional plugin I use (options.nvim) is biting me in the butt. I have it installed and have foolishly not tried it without it. Options.nvim handles setting that variable by default so I forgot about it. If it's not installed, the default variable should be written as part of set up function.

I'll take a look at this today.

**Comment by Furkanzmc** [comment]
I pushed a commit that should this problem. Thanks.
